<?php
/**
 * Solwin Infotech
 * Solwin Instagram Extension
 *
 * @category   Solwin
 * @package    Solwin_Instagram
 * @copyright  Copyright © 2006-2016 Solwin (https://www.solwininfotech.com)
 * @license    https://www.solwininfotech.com/magento-extension-license/
 */
$helper = $this->helper('\Solwin\Instagram\Helper\Data');
$enable = $helper->getConfig('instagramsection/instagramgroup/active');
$userId = $helper->getConfig('instagramsection/instagramgroup/userid');
$accessToken = $helper->getConfig('instagramsection/instagramgroup/accesstoken');
$imageNumber = $this->getData('numberimage');
?>

<?php
if ($enable) {
    ?>
    <div class="instagram_block_home">
        <div class="container">
            <div class="cp-ftitle">
                <h3><?php echo $this->getData('title'); ?></h3>
                <p><?php echo __("@bstore_au") ?></p>
            </div>
            <div class="row">
                <div class="cp-fcontent">
                    <?php

                    $url = 'https://api.instagram.com/v1/users/' . $userId . '/media/recent/?access_token=' . $accessToken;

                    $args = stream_context_create(array('http' => array('timeout' => 2500,)));
                    //for Live server
                    $instagramFeedsData = file_get_contents($url, false, $args );
                    // for local server
                    // $instagramFeedsData = $helper->getInstangramData($url);

                    $instagramFeeds = json_decode($instagramFeedsData);

                    $instangramData = $instagramFeeds->data;
                    $username = $instangramData[0]->user->username;
                    $url_user = 'https://instagram.com/' . $username;
                    $count = 1;
                    foreach ($instangramData as $instagramFeed) {

                        if ($imageNumber < $count) {
                            break;
                        }
                        $instagramImage = $instagramFeed->images->standard_resolution->url;
                        $count++;
                        ?>

                        <?php
                        $caption_text = 'Instagram';
                        if (is_object($instagramFeed->caption)) {
                            $caption_text = $instagramFeed->caption->text;
                        }
                        ?>
                        <div class="instangram-feed">

                            <a href ="<?php echo $instagramFeed->link; ?>" target="_blank">
                                <img   src="<?php echo $instagramImage; ?>" title="<?php echo $caption_text; ?>" alt="<?php echo $caption_text; ?>"/>
                            </a>
                        </div>
                        <?php
                    }
                    ?>
                </div>
                <div class="button-instagram">
                    <a target="_blank" href="<?php echo $url_user?>"><?php echo __("View our instagram");?></a>
                </div>
            </div>
        </div>
    </div>
    <?php
}
?>
<script type="text/javascript">
    require([
        'jquery',
        'SlickSlider'
    ],function($){
        'use strict';
        $(document).ready(function(){
            $('.cp-fcontent').slick({
                dots: false,
                infinite: false,
                speed: 300,
                slidesToShow: 6,
                slidesToScroll: 1,
                responsive: [
                    {
                        breakpoint: 992,
                        settings: {
                            slidesToShow: 4,
                            slidesToScroll: 4,
                            infinite: true,
                            dots: false
                        }
                    },
                    {
                        breakpoint: 767,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 2
                        }
                    }
                ]
            });

        });
    });


</script>
